#version 450
precision highp float;
precision highp int;
layout(set = 2, binding = 0) uniform sampler2D opaqueColor;
layout(set = 2, binding = 1) uniform sampler2D opaqueDepth;
layout(set = 2, binding = 2) uniform samplerCube waterSky;
layout(push_constant) uniform WaterPush {
    mat4 invViewProj;
    vec4 camera;
    vec4 params; // height, half size, roughness, time
    vec4 color;
} water;
layout(location = 0) in vec2 vTexCoord;
layout(location = 0) out vec4 outColor;
#define WATER_INV water.invViewProj
#define WATER_CAMERA water.camera
#define WATER_PARAMS water.params
#define WATER_COLOR water.color
#define WATER_UV vTexCoord
#define DEPTH_NDC depth
#define WATER_LDR false
// Four advected noise octaves with analytic height gradients. Geometry stays
// at the fixed sea level; only the reflection normal changes.
float WaterHash(vec2 p)
{
    vec3 q = fract(vec3(p.xyx) * 0.1031);
    q += dot(q, q.yzx + 33.33);
    return fract((q.x + q.y) * q.z);
}

vec2 WaterNoiseGradient(vec2 p)
{
    vec2 cell = floor(p);
    vec2 f = fract(p);
    // Quintic interpolation gives continuous first and second derivatives
    // across lattice boundaries, without finite-difference texture samples.
    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    vec2 du = 30.0 * f * f * (f * (f - 2.0) + 1.0);
    float a = WaterHash(cell);
    float b = WaterHash(cell + vec2(1.0, 0.0));
    float c = WaterHash(cell + vec2(0.0, 1.0));
    float d = WaterHash(cell + vec2(1.0, 1.0));
    return vec2(mix(b - a, d - c, u.y) * du.x,
                mix(c - a, d - b, u.x) * du.y);
}

vec3 WaterNormal(vec3 worldPosition, float time)
{
    vec2 p = worldPosition.xz;
    float footprint = max(length(dFdx(p)), length(dFdy(p)));
    const mat2 turn = mat2(0.8, 0.6, -0.6, 0.8);
    mat2 basis = mat2(1.0);
    vec2 drift = vec2(0.12, -0.08);
    vec2 offset = vec2(17.3, -9.2);
    vec2 slope = vec2(0.0);
    float frequency = 0.45;
    float amplitude = 0.24;
    for (int octave = 0; octave < 4; ++octave) {
        // Each layer has its own scale, orientation, origin and flow direction.
        vec2 q = basis * p * frequency + drift * (time * 3.0) + offset;
        float filterWeight = 1.0 - smoothstep(0.25, 0.85, footprint * frequency);
        slope += transpose(basis) * WaterNoiseGradient(q)
            * (amplitude * frequency * filterWeight);
        basis = turn * basis;
        drift = turn * drift * 1.19;
        offset = turn * offset + vec2(23.7, 11.9);
        frequency *= 2.17;
        amplitude *= 0.43;
    }
    return normalize(vec3(-slope.x, 1.0, -slope.y));
}


vec3 ReconstructWorld(vec2 uv, float depth)
{
    vec4 h = WATER_INV * vec4(uv * 2.0 - 1.0, DEPTH_NDC, 1.0);
    return h.xyz / h.w;
}

// Analytic camera-facing billboard discs, composited in linear HDR before
// bloom. Positions/colors match scene lights; emission has its own gain.
vec3 LightBillboard(vec3 camera, vec3 ray, float sceneDistance,
    vec3 center, vec3 radiance)
{
    vec3 toCenter = center - camera;
    float centerDistance = length(toCenter);
    if (centerDistance < 0.001) return vec3(0.0);
    vec3 facing = toCenter / centerDistance;
    float denominator = dot(ray, facing);
    if (denominator <= 0.0001) return vec3(0.0);
    float t = centerDistance / denominator;
    if (t >= sceneDistance - 0.001) return vec3(0.0);
    const float radius = 0.12; // world metres, perspective scales naturally
    float radial = length(camera + ray*t - center) / radius;
    // Solid emissive disc: no translucent rim, Gaussian tail or fake halo.
    // All light outside the disc is generated by the downstream bloom pass.
    if (radial > 1.0) return vec3(0.0);
    return radiance * 16.6;
}

vec3 SceneLightBillboards(vec3 camera, vec3 ray, float sceneDistance)
{
    return LightBillboard(camera, ray, sceneDistance,
        vec3(12.0,-0.64,-12.0), vec3(1.0,0.12,0.10)*8.0) +
        LightBillboard(camera, ray, sceneDistance,
        vec3(0.0,-0.64,0.0), vec3(0.10,0.25,1.0)*8.0) +
        LightBillboard(camera, ray, sceneDistance,
        vec3(-5.0,-0.64,5.0), vec3(0.10,1.0,0.18)*8.0);
}

vec4 FinishScene(vec3 color, vec3 camera, vec3 ray, float sceneDistance)
{
    vec3 emitter = SceneLightBillboards(camera, ray, sceneDistance);
    if (max(max(emitter.r, emitter.g), emitter.b) > 0.0) color = emitter;
    if (WATER_LDR) {
        color *= 1.8;
        color = pow(max(color / (color + vec3(1.0)), vec3(0.0)), vec3(1.0 / 2.2));
    }
    return vec4(color, 1.0);
}

void main()
{
    vec2 uv = WATER_UV;
    vec3 source = texture(opaqueColor, uv).rgb;
    if (WATER_CAMERA.w < 0.5) { outColor = vec4(source, 1.0); return; }
    vec3 background = source;
    if (WATER_LDR) {
        vec3 mapped = pow(max(source, vec3(0.0)), vec3(2.2));
        background = mapped / max(vec3(1.0) - mapped, vec3(0.0001)) / 1.8;
    }
    ivec2 extent = textureSize(opaqueDepth, 0);
    ivec2 pixel = clamp(ivec2(uv * vec2(extent)), ivec2(0), extent - ivec2(1));
    float depth = texelFetch(opaqueDepth, pixel, 0).r;
    vec3 camera = WATER_CAMERA.xyz;
    vec3 bottom = ReconstructWorld(uv, depth);
    vec3 ray = normalize(ReconstructWorld(uv, 1.0) - camera);
    float bottomDistance = depth >= 0.99999 ? 10000.0 : max(dot(bottom - camera, ray), 0.0);
    float surfaceDistance = abs(ray.y) > 0.00001 ? (WATER_PARAMS.x - camera.y) / ray.y : -1.0;
    vec3 surface = camera + ray * max(surfaceDistance, 0.0);
    bool insideSea = abs(surface.x) <= WATER_PARAMS.y && abs(surface.z) <= WATER_PARAMS.y;
    bool hitsWater = WATER_CAMERA.w < 1.5 && insideSea && surfaceDistance > 0.0 && surfaceDistance < bottomDistance - 0.001;
    bool underwater = WATER_CAMERA.w < 1.5 && camera.y < WATER_PARAMS.x && abs(camera.x) <= WATER_PARAMS.y && abs(camera.z) <= WATER_PARAMS.y;
    vec3 waveNormal = WaterNormal(surface, WATER_PARAMS.w);
    if (!hitsWater && !underwater) {
        outColor = FinishScene(background, camera, ray, bottomDistance); return;
    }

    // Retained opaque depth gives the submerged optical path in world units.
    float pathLength = underwater ? (hitsWater ? surfaceDistance : bottomDistance) : bottomDistance - surfaceDistance;
    pathLength = clamp(pathLength, 0.0, 60.0);
    // Beer-Lambert: red is absorbed first; blue/green penetrate farther.
    vec3 transmission = exp(-vec3(0.45, 0.12, 0.06) * pathLength);
    vec3 body = pow(max(WATER_COLOR.rgb, vec3(0.0)), vec3(2.2));
    vec3 throughWater = background * transmission + body * (vec3(1.0) - transmission);
    vec3 color = throughWater;
    if (hitsWater) {
        vec3 N = waveNormal;
        vec3 V = -ray;
        if (dot(N, V) < 0.0) N = -N;
        float NoV = clamp(dot(N, V), 0.0, 1.0);
        float fresnel = 0.02 + 0.98 * pow(1.0 - NoV, 5.0);
        vec3 reflected = pow(max(textureLod(waterSky, reflect(ray, N), WATER_PARAMS.z * 4.0).rgb,
                                 vec3(0.0)), vec3(2.2));
        color = mix(throughWater, reflected, fresnel);
    }
    // A visible water surface also occludes submerged light markers.
    float visibleDistance = hitsWater ? min(surfaceDistance, bottomDistance) : bottomDistance;
    outColor = FinishScene(color, camera, ray, visibleDistance);
}
