#!/usr/bin/env python
"""Regenerate scene_shaders_spv_vulkan.h from the GLSL sources in application/shaders.

Usage:
    python build_scene_shaders.py

Requires glslang_validator (shipped with the OpenHarmony / HarmonyOS SDK):
    <sdk>/default/openharmony/toolchains/glslang_validator.exe

The generated header embeds every shader as a C array of uint32_t words plus
a word-count constant, inside namespace `native_vulkan_scene`, which is what
application/vulkan_sdl.cpp consumes.
"""
import os
import re
import struct
import subprocess
import sys

GLSLANG = os.environ.get(
    "GLSLANG",
    "D:/Program Files/Huawei/DevEco Studio/sdk/default/openharmony/toolchains/glslang_validator.exe",
)
SHADER_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "shaders")
HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "scene_shaders_spv_vulkan.h")

# (glsl file, array symbol, word-count symbol)
SHADERS = [
    ("scene_cube.vert", "kSceneCubeVertSpv", "kSceneCubeVertSpvWordCount"),
    ("scene_cube.frag", "kSceneCubeFragSpv", "kSceneCubeFragSpvWordCount"),
    ("scene_skybox.vert", "kSceneSkyboxVertSpv", "kSceneSkyboxVertSpvWordCount"),
    ("scene_skybox.frag", "kSceneSkyboxFragSpv", "kSceneSkyboxFragSpvWordCount"),
    ("scene_ibl.vert", "kSceneIblVertSpv", "kSceneIblVertSpvWordCount"),
    ("scene_ibl_irradiance.frag", "kSceneIblIrradianceFragSpv", "kSceneIblIrradianceFragSpvWordCount"),
    ("scene_ibl_prefilter.frag", "kSceneIblPrefilterFragSpv", "kSceneIblPrefilterFragSpvWordCount"),
    ("scene_shadow.vert", "kSceneShadowVertSpv", "kSceneShadowVertSpvWordCount"),
    ("scene_shadow.frag", "kSceneShadowFragSpv", "kSceneShadowFragSpvWordCount"),
    ("scene_model.vert", "kSceneModelVertSpv", "kSceneModelVertSpvWordCount"),
    ("scene_model.frag", "kSceneModelFragSpv", "kSceneModelFragSpvWordCount"),
    ("scene_overlay.vert", "kSceneOverlayVertSpv", "kSceneOverlayVertSpvWordCount"),
    ("scene_overlay.frag", "kSceneOverlayFragSpv", "kSceneOverlayFragSpvWordCount"),
    ("scene_icon.vert", "kSceneIconVertSpv", "kSceneIconVertSpvWordCount"),
    ("scene_icon.frag", "kSceneIconFragSpv", "kSceneIconFragSpvWordCount"),
    ("scene_text.vert", "kSceneTextVertSpv", "kSceneTextVertSpvWordCount"),
    ("scene_text.frag", "kSceneTextFragSpv", "kSceneTextFragSpvWordCount"),
    ("scene_post.vert", "kScenePostVertSpv", "kScenePostVertSpvWordCount"),
    ("scene_post.frag", "kScenePostFragSpv", "kScenePostFragSpvWordCount"),
    ("scene_water.frag", "kSceneWaterFragSpv", "kSceneWaterFragSpvWordCount"),
    ("scene_bloom_threshold.frag", "kSceneBloomThresholdFragSpv", "kSceneBloomThresholdFragSpvWordCount"),
    ("scene_bloom_down.frag", "kSceneBloomDownFragSpv", "kSceneBloomDownFragSpvWordCount"),
    ("scene_bloom_up.frag", "kSceneBloomUpFragSpv", "kSceneBloomUpFragSpvWordCount"),
]

STAGE_BY_EXT = {".vert": "vert", ".frag": "frag"}


def compile_shader(glsl_path):
    """Compile one GLSL file to SPIR-V and return the uint32 words."""
    stage = STAGE_BY_EXT[os.path.splitext(glsl_path)[1]]
    tmp = os.path.join(os.environ.get("TEMP", "/tmp"), os.path.basename(glsl_path) + ".spv")
    cmd = [GLSLANG, "-V", "--target-env", "vulkan1.0", glsl_path, "-o", tmp]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write("glslang failed for %s (stage=%s)\n%s%s\n"
                         % (glsl_path, stage, result.stdout, result.stderr))
        raise SystemExit(1)
    data = open(tmp, "rb").read()
    os.remove(tmp)
    if len(data) % 4 != 0:
        raise SystemExit("SPIR-V size not a multiple of 4: %s" % glsl_path)
    words = struct.unpack("<%dI" % (len(data) // 4), data)
    if words[0] != 0x07230203:
        raise SystemExit("bad SPIR-V magic in %s" % glsl_path)
    return words


def format_words(words):
    """Emit 8 words per line, tab-indented, matching the existing style."""
    lines = []
    for i in range(0, len(words), 8):
        chunk = words[i:i + 8]
        lines.append("\t" + ",".join("0x%08x" % w for w in chunk) + ",")
    if lines:
        # Strip the trailing comma from the very last line.
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def main():
    if not os.path.exists(GLSLANG):
        raise SystemExit("glslang_validator not found at %s" % GLSLANG)

    parts = [
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "// Generated by build_scene_shaders.py -- do not edit by hand.",
        "// Source of truth: application/shaders/*.vert and *.frag",
        "",
        "namespace native_vulkan_scene {",
        "",
    ]

    for filename, array_name, count_name in SHADERS:
        glsl_path = os.path.join(SHADER_DIR, filename)
        if not os.path.exists(glsl_path):
            raise SystemExit("missing shader source: %s" % glsl_path)
        words = compile_shader(glsl_path)
        parts.append("static const std::uint32_t %s[] = {" % array_name)
        parts.append(format_words(words))
        parts.append("};")
        parts.append("static const std::size_t %s = sizeof(%s) / sizeof(%s[0]);"
                     % (count_name, array_name, array_name))
        parts.append("")

    parts.append("} // namespace native_vulkan_scene")
    parts.append("")

    with open(HEADER, "w", newline="\n") as handle:
        handle.write("\n".join(parts))

    print("wrote %s" % HEADER)
    for filename, array_name, count_name in SHADERS:
        glsl_path = os.path.join(SHADER_DIR, filename)
        print("  %-20s -> %s" % (filename, array_name))


if __name__ == "__main__":
    main()
